#!/bin/bash
#shellcheck disable=SC2034

set -o errexit
set -o pipefail
set -o xtrace

# Define useful variables
WAR_FILENAME=WebMIaS/target/WebMIaS-"$IMAGE_TAG"-SNAPSHOT.war
IMAGE_TAG=miratmu/"$IMAGE_TAG"

set -o nounset

# Define command aliases
docker_build() {
  docker build --build-arg WAR_FILENAME="$WAR_FILENAME" --compress --no-cache --force-rm --squash -t "$IMAGE_TAG" "$@"
}

docker_run() {
  docker run --rm -u "$(id -u)":"$(id -g)" -v "$PWD":/data -w /data "$1" "${@:2}"
}

mias() {
  docker_run miratmu/MIaS "$@"
}

webmias() {
  docker_run "$IMAGE_TAG" "$@"
}
