#!/bin/bash
#shellcheck disable=SC2034

set -o errexit
set -o pipefail
set -o xtrace

# Define useful variables
WAR_FILENAME=WebMIaS/target/WebMIaS-"$IMAGE_TAG"-SNAPSHOT.war
MIAS_IMAGE_TAG=miratmu/mias:"$IMAGE_TAG"
IMAGE_TAG=miratmu/webmias:"$IMAGE_TAG"

set -o nounset

# Define command aliases
docker_build() {
  docker build --build-arg WAR_FILENAME="$WAR_FILENAME" --compress --no-cache --force-rm --squash -t "$IMAGE_TAG" "$@"
  docker tag "$IMAGE_TAG" miratmu/webmias:latest
}

docker_push() {
  docker push "$IMAGE_TAG"
  docker push miratmu/webmias:latest
}

mias() {
  docker run -v "$(readlink -f "$1")":/dataset:ro -v "$(readlink -f "$2")":/index:rw \
    --rm "$MIAS_IMAGE_TAG"
}

webmias_start() {
  docker run -v "$(readlink -f "$1")":/dataset:ro -v "$(readlink -f "$2")":/index:ro \
    --rm --name webmias -d -p 127.0.0.1:8888:8080 "$IMAGE_TAG"
}

webmias_query() {
  curl -fsSL 'http://localhost:8888/WebMIaS/ws/search' \
    --data-raw 'variant=pcmath&query=+%24e%3Dmc%5E2%24'
}

webmias_stop() {
  docker stop webmias
}
